# -*- coding: utf-8 -*-
"""semtiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oL2yRTcKuwRuDGVYQSq3l4t7KLllG36i
"""

import tweepy

from textblob import TextBlob

keyword = input("input the keyword you want to search")

import csv

consumer_key = '2B77Xu6YkilL4W3iqbiNPox8p'

consumer_secret = 'XmwC28Os6ZIClZlWEbugSuUEpScF6xIbiS24wyPjwr1gVXKpqs'

access_token = '3258563641-GFxCwNUW2KYhjrX4cl9ZLNh1K0aRYxYjw243xXq'

access_token_secret = 'YB5HYyx7cdaoZYl8n4hvjhUzwycIbcZkpvlmg0wBJwSPO'

auth = tweepy.OAuthHandler(consumer_key,consumer_secret)

auth.set_access_token(access_token,access_token_secret)

api = tweepy.API(auth)

public_tweets = api.search(keyword)

f = open("test.csv","w+")
f.write('tweet'+'\t'+'sentiment analysis\n')
for tweet in public_tweets:
  analysis = TextBlob(tweet.text)
  x = analysis.sentiment.polarity 
  if x < 0:
    c = 'negative' 
  elif x == 0:
    c='neutral'
  else:
    c='positive'
  f.write("{} \t {}\n".format(tweet.text,(str)(c)+'('+(str)(x)+')'))

f.close()

